force-app/main/default/objects/Revenue_Contract__c/Revenue_Contract__c.object-meta.xml
<CustomObject>
    <label>Revenue Contract</label>
    <nameField>
        <label>Revenue Contract Id</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Revenue Contracts</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Revenue_Contract__c/fields/Billed_Amount__c.field-meta.xml
<CustomField>
    <fullName>Billed_Amount__c</fullName>
    <label>Billed Amount</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Revenue_Contract__c/fields/Carves_Currency_Code__c.field-meta.xml
<CustomField>
    <fullName>Carves_Currency_Code__c</fullName>
    <label>Carves Currency Code</label>
    <length>10</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Revenue_Contract_Line__c/Revenue_Contract_Line__c.object-meta.xml
<CustomObject>
    <label>Revenue Contract Line</label>
    <nameField>
        <displayFormat>RCL-{00000}</displayFormat>
        <label>RC Line ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Revenue Contract Lines</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Revenue_Contract_Line__c/fields/Above_Mid_Point__c.field-meta.xml
<CustomField>
    <fullName>Above_Mid_Point__c</fullName>
    <label>Above Mid Point %</label>
    <precision>18</precision>
    <scale>3</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Revenue_Contract_Line__c/fields/Allocated_Amount__c.field-meta.xml
<CustomField>
    <fullName>Allocated_Amount__c</fullName>
    <label>Allocated Amount (Net Revenue)</label>
    <precision>18</precision>
    <scale>3</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Revenue_Contract_Line__c/fields/Line_Term__c.field-meta.xml
<CustomField>
    <fullName>Line_Term__c</fullName>
    <label>Line Term</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Revenue_Contract_Line__c/fields/Revenue_Contract_id__c.field-meta.xml
<CustomField>
    <fullName>Revenue_Contract_id__c</fullName>
    <label>Revenue Contract ID</label>
    <referenceTo>Revenue_Contract__c</referenceTo>
    <relationshipLabel>Revenue Contract Lines</relationshipLabel>
    <relationshipName>Revenue_Contract_Lines</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/classes/QueryServiceTest.cls
@isTest
public class QueryServiceTest {
    @istest
    static void queryTest() {
        String nameSpaceString = Utility.getNameSpace();
        List<string> fieldList = new List<string>();
        String name = 'Name';
        fieldList.add(name);
        String revenue = 'Revenue_Contract__c';
        String revenueLine = 'Revenue_Contract_Lines__r';
        String filter = 'Name != null';
        Integer num = 2;
        String order = 'Line_Term__c ASC';
        Test.startTest();
        QueryService query = new QueryService(fieldList, revenue);
        query.setWhereClause(filter);
        query.setLimit(num);
        query.setOrderBy(order);
        String str = query.toSQL();
        system.assertEquals('SELECT Name FROM ' + nameSpaceString + 'Revenue_Contract__c WHERE Name != null ORDER BY Line_Term__c ASC LIMIT 2', str);
        Test.stopTest();
    }

    @isTest
    private static void testRelationshipQuery() {
        String nameSpaceString = Utility.getNameSpace();
        Test.startTest();
        QueryService q = new QueryService(new List<String>{ 'Billed_Amount__c', 'Carves_Currency_Code__c' }, 'Revenue_Contract__c', new Map<String, List<String>>{ 'Revenue_Contract_Lines__r' => new List<String>{ 'Above_Mid_point__c', 'Allocated_Amount__c' } });
        q.setWhereClause('Billed_Amount__c != null');
        String genQuery = q.toSQL();
        Test.stopTest();
        System.assertNotEquals(null, genQuery);
    }

}