force-app/main/default/objects/Line_Met_Dimension__c/Line_Met_Dimension__c.object-meta.xml
<CustomObject>
    <label>Line Metric Dimension</label>
    <nameField>
        <displayFormat>LMD-{0000}</displayFormat>
        <label>Line Metric Dimension Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Line Metric Dimensions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Line_Met_Dimension__c/fields/Revenue_Contract_ID__c.field-meta.xml
<CustomField>
    <fullName>Revenue_Contract_ID__c</fullName>
    <label>Revenue Contract ID</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Line_Met_Dimension__c/fields/Revenue_Contract_Line__c.field-meta.xml
<CustomField>
    <fullName>Revenue_Contract_Line__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Revenue Contract Line</label>
    <referenceTo>Revenue_Contract_Line__c</referenceTo>
    <relationshipLabel>Line Metric Dimensions</relationshipLabel>
    <relationshipName>Line_Met_Dimensions</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Rev_Summary__c/Rev_Summary__c.object-meta.xml
<CustomObject>
    <label>Revenue Summary</label>
    <nameField>
        <displayFormat>RS-{00000}</displayFormat>
        <label>Revenue Summary Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Revenue Summary</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Rev_Summary__c/fields/Revenue_Contract_Id__c.field-meta.xml
<CustomField>
    <fullName>Revenue_Contract_Id__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Revenue Contract Id</label>
    <referenceTo>Revenue_Contract__c</referenceTo>
    <relationshipLabel>Revenue Summary</relationshipLabel>
    <relationshipName>Rev_Summary</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Revenue_Contract__c/Revenue_Contract__c.object-meta.xml
<CustomObject>
    <label>Revenue Contract</label>
    <nameField>
        <label>Revenue Contract Id</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Revenue Contracts</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Revenue_Contract__c/fields/Bg_Run_ID__c.field-meta.xml
<CustomField>
    <fullName>Bg_Run_ID__c</fullName>
    <label>Bg Run ID</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Revenue_Contract__c/fields/Revenue_Contract_GUID__c.field-meta.xml
<CustomField>
    <fullName>Revenue_Contract_GUID__c</fullName>
    <caseSensitive>true</caseSensitive>
    <externalId>true</externalId>
    <label>Revenue Contract GUID</label>
    <length>36</length>
    <required>true</required>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Revenue_Contract__c/recordTypes/MJE_RC.recordType-meta.xml
<RecordType>
    <fullName>MJE_RC</fullName>
    <active>true</active>
    <label>MJE RC</label>
</RecordType>

force-app/main/default/objects/Revenue_Contract__c/recordTypes/RC.recordType-meta.xml
<RecordType>
    <fullName>RC</fullName>
    <active>true</active>
    <label>RC</label>
</RecordType>

force-app/main/default/objects/Revenue_Contract_Line__c/Revenue_Contract_Line__c.object-meta.xml
<CustomObject>
    <label>Revenue Contract Line</label>
    <nameField>
        <displayFormat>RCL-{00000}</displayFormat>
        <label>RC Line ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Revenue Contract Lines</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Revenue_Contract_Line__c/fields/Bg_Run_ID__c.field-meta.xml
<CustomField>
    <fullName>Bg_Run_ID__c</fullName>
    <label>Bg Run ID</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Revenue_Contract_Line__c/fields/Revenue_Contract_id__c.field-meta.xml
<CustomField>
    <fullName>Revenue_Contract_id__c</fullName>
    <label>Revenue Contract ID</label>
    <referenceTo>Revenue_Contract__c</referenceTo>
    <relationshipLabel>Revenue Contract Lines</relationshipLabel>
    <relationshipName>Revenue_Contract_Lines</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Revenue_Contract_Waterfall__c/Revenue_Contract_Waterfall__c.object-meta.xml
<CustomObject>
    <label>Revenue Contract Waterfall</label>
    <nameField>
        <displayFormat>WF-{000}</displayFormat>
        <label>Revenue Waterfall Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Revenue Contract Waterfalls</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Revenue_Contract_Waterfall__c/fields/Revenue_Contract_GUID__c.field-meta.xml
<CustomField>
    <fullName>Revenue_Contract_GUID__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Revenue Contract</label>
    <referenceTo>Revenue_Contract__c</referenceTo>
    <relationshipLabel>Revenue Contract Waterfalls</relationshipLabel>
    <relationshipName>Revenue_Contract_Waterfalls</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Revenue_Contract_Waterfall__c/fields/Revenue_Contract_Id__c.field-meta.xml
<CustomField>
    <fullName>Revenue_Contract_Id__c</fullName>
    <label>Revenue Contract Id</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Revenue_Contract_Waterfall__c/fields/Revenue_Contract_Line__c.field-meta.xml
<CustomField>
    <fullName>Revenue_Contract_Line__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Revenue Contract Line</label>
    <referenceTo>Revenue_Contract_Line__c</referenceTo>
    <relationshipLabel>Revenue Contract Waterfalls</relationshipLabel>
    <relationshipName>Revenue_Contract_Waterfalls</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/RCJsonDeleteBatch.cls
public with sharing class RCJsonDeleteBatch implements Database.Batchable<SObject>, Database.stateful {
    private List<String> lstInputValues = new List<String>();
    private String strRunId;

    private String strObjName;

    public RCJsonDeleteBatch(List<String> lstInputs, String runId, String objName) {
        lstInputValues = lstInputs;
        strRunId = runId;
        strObjName = objName;
    }

    public Database.QueryLocator start(Database.BatchableContext bc) {
        return Database.getQueryLocator(getQuery(strObjName));
    }

    private String getQuery(String strObjectName) {
        QueryService qs = new QueryService(new List<String>{ Constants.FIELD_ID }, strObjectName);
        switch  on strObjectName {
            when 'Revenue_Contract_Waterfall__c' {
                qs.setWhereClause('Revenue_Contract_GUID__r.Name IN :lstInputValues AND Bg_Run_ID__c != :strRunId');
            }
            when 'Revenue_Contract_Line__c' {
                qs.setWhereClause('Revenue_Contract_id__r.Name IN :lstInputValues AND Bg_Run_ID__c != :strRunId');
            }
            when 'Rev_Summary__c' {
                qs.setWhereClause('Revenue_Contract_Id__r.Name IN :lstInputValues AND Bg_Run_ID__c != :strRunId');
            }
            when 'Line_Met_Dimension__c' {
                qs.setWhereClause('Revenue_Contract_ID__c IN :lstInputValues AND Bg_Run_ID__c != :strRunId');
            }
            when 'Revenue_Contract__c' {
                qs = new QueryService(new List<String>{ Constants.FIELD_ID, 'Name', 'RecordTypeId' }, strObjectName);
                qs.setWhereClause('Name IN : lstInputValues');
            }
        }
        return qs.toSQL();
    }

    public void execute(Database.BatchableContext bc, List<SObject> scope) {
        try {
            switch  on strObjName {
                when 'Revenue_Contract__c' {
                    List<Revenue_Contract__c> lstRCLRecords = (List<Revenue_Contract__c>)scope;
                    List<Revenue_Contract__c> lstRecords = new List<Revenue_Contract__c>();
                    Map<String, Schema.RecordTypeInfo> mapRecordType = Schema.SObjectType.Revenue_Contract__c.getRecordTypeInfosByDeveloperName();
                    Id rcRecordTypeId = mapRecordType.get(Constants.RC).getRecordTypeId();
                    Id mjeRecordTypeId = mapRecordType.get('MJE_RC').getRecordTypeId();
                    for (Revenue_Contract__c record : lstRCLRecords) {
                        //recordType mapping from Name
                        Id correctRecordTypeId = record.Name.startsWith('RC-') ? rcRecordTypeId : mjeRecordTypeId;
                        if (record.RecordTypeId != correctRecordTypeId) {
                            record.RecordTypeId = correctRecordTypeId;
                            lstRecords.add(record);
                        }
                    }
                    update (lstRecords);
                }
                when else {
                    delete (scope);
                }
            }
        } catch (Exception ex) {
            throw ex;
        }
    }

    public void finish(Database.BatchableContext bc) {
        AsyncApexJob job = [SELECT Id, ExtendedStatus, Status, JobItemsProcessed, TotalJobItems, NumberOfErrors
                            FROM AsyncApexJob
                            WHERE Id = :bc.getJobId()];
        if (job.NumberOfErrors > 0 || Test.isRunningTest()) {
            String strJobDetails = JSON.serialize(job);
            EmailWrapper emailWrap = new EmailWrapper();
            emailWrap.strProcessName = strObjName.capitalize();
            emailWrap.className = 'RCJsonDeleteBatch';
            emailWrap.message = strJobDetails;
            emailWrap.subject = 'RC DELETE';
            emailWrap.senderDisplayName = 'Batch Process';
            createAndSendEmail(emailWrap);
        }
    }

    public static Id executeBatch(List<String> lstInputValues, String strRunId, String strObjName) {
        RCJsonDeleteBatch batchClass = new RCJsonDeleteBatch(lstInputValues, strRunId, strObjName);
        String strQuery = batchClass.getQuery(strObjName);
        Integer intRecordSize = Database.countQuery(Constants.SOQL_SELECT + 'Count()' + Constants.SOQL_FROM + strQuery.substringAfter(Constants.SOQL_FROM));
        if (intRecordSize > 0) {
            return Database.executeBatch(batchClass, 2000);
        }
        return null;
    }
    
    private static void createAndSendEmail(EmailWrapper emailWrap) {
        Messaging.SingleEmailMessage mail = new Messaging.SingleEmailMessage();
        if (emailWrap != null) {
            EmailTemplate emailTemplate = [SELECT Id, HtmlValue, Body
                                           FROM EmailTemplate
                                           WHERE DeveloperName = 'RightRev_Post_Upgrade_Status'
                                           WITH SECURITY_ENFORCED
                                           LIMIT 1];
            String htmlBody = emailTemplate.HtmlValue;
            String strOrgId = UserInfo.getOrganizationId();
            String strOrgURL = URL.getOrgDomainURL().toExternalForm();
            String strOrgName = UserInfo.getOrganizationName();
            htmlBody = htmlBody.replace('methodName', emailWrap.strProcessName);
            htmlBody = htmlBody.replace('{!Organization.Id}', strOrgId);
            htmlBody = htmlBody.replace('className', emailWrap.className);
            htmlBody = htmlBody.replace('{!OrganizationURL}', strOrgURL);
            htmlBody = htmlBody.replace('{!Organization.Name}', strOrgName);
            htmlBody = htmlBody.replace('{!URL}', strOrgURL);
            htmlBody = htmlBody.replace('{!Message}', emailWrap.message);
            String plainBody = emailTemplate.Body;
            plainBody = plainBody.replace('methodName', emailWrap.strProcessName);
            plainBody = plainBody.replace('{!Organization.Id}', strOrgId);
            plainBody = plainBody.replace('className', emailWrap.className);
            plainBody = plainBody.replace('{!Organization.Name}', strOrgName);
            plainBody = plainBody.replace('{!OrganizationURL}', strOrgURL);
            plainBody = plainBody.replace('{!Message}', emailWrap.message);
            mail.setToAddresses(new String[]{ Constants.INTEGRATION_USER_EMAIL });
            mail.setSenderDisplayName(emailWrap.senderDisplayName);
            mail.setSubject(emailWrap.subject);
            mail.setHtmlBody(htmlBody);
            mail.setPlainTextBody(plainBody);
            Messaging.SendEmailResult[] results = Messaging.sendEmail(new Messaging.SingleEmailMessage[]{ mail }, false);
        }
    }

    public class EmailWrapper {
        public String strDMLType;

        public String strProcessName;

        public String className;

        public String message;

        public String subject;

        public String senderDisplayName;

    }

}