force-app/main/default/objects/Line_Met_Dimension__c/Line_Met_Dimension__c.object-meta.xml
<CustomObject>
    <label>Line Metric Dimension</label>
    <nameField>
        <displayFormat>LMD-{0000}</displayFormat>
        <label>Line Metric Dimension Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Line Metric Dimensions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Line_Met_Dimension__c/fields/Revenue_Contract_ID__c.field-meta.xml
<CustomField>
    <fullName>Revenue_Contract_ID__c</fullName>
    <label>Revenue Contract ID</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Line_Met_Dimension__c/fields/Revenue_Contract_Line__c.field-meta.xml
<CustomField>
    <fullName>Revenue_Contract_Line__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Revenue Contract Line</label>
    <referenceTo>Revenue_Contract_Line__c</referenceTo>
    <relationshipLabel>Line Metric Dimensions</relationshipLabel>
    <relationshipName>Line_Met_Dimensions</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Rev_Summary__c/Rev_Summary__c.object-meta.xml
<CustomObject>
    <label>Revenue Summary</label>
    <nameField>
        <displayFormat>RS-{00000}</displayFormat>
        <label>Revenue Summary Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Revenue Summary</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Rev_Summary__c/fields/Revenue_Contract_Id__c.field-meta.xml
<CustomField>
    <fullName>Revenue_Contract_Id__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Revenue Contract Id</label>
    <referenceTo>Revenue_Contract__c</referenceTo>
    <relationshipLabel>Revenue Summary</relationshipLabel>
    <relationshipName>Rev_Summary</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Revenue_Contract__c/Revenue_Contract__c.object-meta.xml
<CustomObject>
    <label>Revenue Contract</label>
    <nameField>
        <label>Revenue Contract Id</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Revenue Contracts</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Revenue_Contract__c/fields/Revenue_Contract_GUID__c.field-meta.xml
<CustomField>
    <fullName>Revenue_Contract_GUID__c</fullName>
    <caseSensitive>true</caseSensitive>
    <externalId>true</externalId>
    <label>Revenue Contract GUID</label>
    <length>36</length>
    <required>true</required>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Revenue_Contract_Line__c/Revenue_Contract_Line__c.object-meta.xml
<CustomObject>
    <label>Revenue Contract Line</label>
    <nameField>
        <displayFormat>RCL-{00000}</displayFormat>
        <label>RC Line ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Revenue Contract Lines</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Revenue_Contract_Line__c/fields/Revenue_Contract_id__c.field-meta.xml
<CustomField>
    <fullName>Revenue_Contract_id__c</fullName>
    <label>Revenue Contract ID</label>
    <referenceTo>Revenue_Contract__c</referenceTo>
    <relationshipLabel>Revenue Contract Lines</relationshipLabel>
    <relationshipName>Revenue_Contract_Lines</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Revenue_Contract_Waterfall__c/Revenue_Contract_Waterfall__c.object-meta.xml
<CustomObject>
    <label>Revenue Contract Waterfall</label>
    <nameField>
        <displayFormat>WF-{000}</displayFormat>
        <label>Revenue Waterfall Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Revenue Contract Waterfalls</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Revenue_Contract_Waterfall__c/fields/Revenue_Contract_GUID__c.field-meta.xml
<CustomField>
    <fullName>Revenue_Contract_GUID__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Revenue Contract</label>
    <referenceTo>Revenue_Contract__c</referenceTo>
    <relationshipLabel>Revenue Contract Waterfalls</relationshipLabel>
    <relationshipName>Revenue_Contract_Waterfalls</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Revenue_Contract_Waterfall__c/fields/Revenue_Contract_Id__c.field-meta.xml
<CustomField>
    <fullName>Revenue_Contract_Id__c</fullName>
    <label>Revenue Contract Id</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Revenue_Contract_Waterfall__c/fields/Revenue_Contract_Line__c.field-meta.xml
<CustomField>
    <fullName>Revenue_Contract_Line__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Revenue Contract Line</label>
    <referenceTo>Revenue_Contract_Line__c</referenceTo>
    <relationshipLabel>Revenue Contract Waterfalls</relationshipLabel>
    <relationshipName>Revenue_Contract_Waterfalls</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/RCJsonInboundTest.cls
@IsTest
public class RCJsonInboundTest {
    public static String assertMsg = 'Rest Response should not be empty';
    public static String restURI = '/services/apexrest/RCJson/';
    @TestSetup
    public static void setup() {
        List<Revenue_Contract__c> lstRevContracts = TestDataFactory.createRevenueContract(1);
        insert (lstRevContracts);
        List<Revenue_Contract_Line__c> lstLines = TestDataFactory.createRevenueContractLine(5);
        for (Revenue_Contract_Line__c line : lstLines) {
            line.Revenue_Contract_id__c = lstRevContracts[0].Id;
        }
        insert (lstLines);
        List<Revenue_Contract_Waterfall__c> lstWaterfalls = TestDataFactory.createRevenueContractWaterfall(5);
        for (Revenue_Contract_Waterfall__c waterfall : lstWaterfalls) {
            waterfall.Revenue_Contract_guid__c = lstRevContracts[0].Id;
        }
        insert (lstWaterfalls);
        List<Line_Met_Dimension__c> lstLineMetrics = TestDataFactory.createLineMetricDimension(5);
        for (Line_Met_Dimension__c lineMetric : lstLineMetrics) {
            lineMetric.Revenue_Contract_id__c = lstRevContracts[0].Id;
        }
        insert (lstLineMetrics);
        List<Rev_Summary__c> lstRevSummary = TestDataFactory.createRevenueSummary(5);
        for (Rev_Summary__c revSummary : lstRevSummary) {
            revSummary.Revenue_Contract_id__c = lstRevContracts[0].Id;
        }
        insert (lstRevSummary);
    }

    @IsTest
    static void testDeleteCase() {
        String body = '{"revenue_contract_id":["TestRevenueContract0"]}';
        RestRequest req = new RestRequest();
        RestResponse res = new RestResponse();
        req.requestURI = restURI + '/1234567890';
        req.httpMethod = 'DELETE';
        req.requestBody = Blob.valueOf(body);
        RestContext.request = req;
        RestContext.response = res;
        Test.startTest();
        RCJsonInbound.doDelete();
        System.assert(res.responseBody != null, assertMsg);
        Test.stopTest();
    }
    
    @IsTest
    static void testDeleteCase2() {
        String body = '{"revenue_contract_id":["TestRevenueContract0"]}';
        RestRequest req = new RestRequest();
        RestResponse res = new RestResponse();
        req.requestURI = restURI;
        req.httpMethod = 'DELETE';
        req.requestBody = Blob.valueOf(body);
        RestContext.request = req;
        RestContext.response = res;
        Test.startTest();
        RCJsonInbound.doDelete();
        System.assert(res.responseBody != null, assertMsg);
        Test.stopTest();
    }

}