force-app/main/default/objects/Line_Met_Dimension__c/Line_Met_Dimension__c.object-meta.xml
<CustomObject>
    <label>Line Metric Dimension</label>
    <nameField>
        <displayFormat>LMD-{0000}</displayFormat>
        <label>Line Metric Dimension Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Line Metric Dimensions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Line_Met_Dimension__c/fields/Revenue_Contract_Line__c.field-meta.xml
<CustomField>
    <fullName>Revenue_Contract_Line__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Revenue Contract Line</label>
    <referenceTo>Revenue_Contract_Line__c</referenceTo>
    <relationshipLabel>Line Metric Dimensions</relationshipLabel>
    <relationshipName>Line_Met_Dimensions</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Rev_Summary__c/Rev_Summary__c.object-meta.xml
<CustomObject>
    <label>Revenue Summary</label>
    <nameField>
        <displayFormat>RS-{00000}</displayFormat>
        <label>Revenue Summary Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Revenue Summary</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Revenue_Contract__c/Revenue_Contract__c.object-meta.xml
<CustomObject>
    <label>Revenue Contract</label>
    <nameField>
        <label>Revenue Contract Id</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Revenue Contracts</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Revenue_Contract__c/fields/Bg_Run_ID__c.field-meta.xml
<CustomField>
    <fullName>Bg_Run_ID__c</fullName>
    <label>Bg Run ID</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Revenue_Contract__c/fields/Revenue_Contract_GUID__c.field-meta.xml
<CustomField>
    <fullName>Revenue_Contract_GUID__c</fullName>
    <caseSensitive>true</caseSensitive>
    <externalId>true</externalId>
    <label>Revenue Contract GUID</label>
    <length>36</length>
    <required>true</required>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Revenue_Contract_Line__c/Revenue_Contract_Line__c.object-meta.xml
<CustomObject>
    <label>Revenue Contract Line</label>
    <nameField>
        <displayFormat>RCL-{00000}</displayFormat>
        <label>RC Line ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Revenue Contract Lines</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Revenue_Contract_Line__c/fields/Bg_Run_ID__c.field-meta.xml
<CustomField>
    <fullName>Bg_Run_ID__c</fullName>
    <label>Bg Run ID</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Revenue_Contract_Line__c/fields/Line_Term__c.field-meta.xml
<CustomField>
    <fullName>Line_Term__c</fullName>
    <label>Line Term</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Revenue_Contract_Line__c/fields/Terms__c.field-meta.xml
<CustomField>
    <fullName>Terms__c</fullName>
    <label>Terms</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Revenue_Contract_Waterfall__c/Revenue_Contract_Waterfall__c.object-meta.xml
<CustomObject>
    <label>Revenue Contract Waterfall</label>
    <nameField>
        <displayFormat>WF-{000}</displayFormat>
        <label>Revenue Waterfall Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Revenue Contract Waterfalls</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Revenue_Contract_Waterfall__c/fields/Revenue_Contract_GUID__c.field-meta.xml
<CustomField>
    <fullName>Revenue_Contract_GUID__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Revenue Contract</label>
    <referenceTo>Revenue_Contract__c</referenceTo>
    <relationshipLabel>Revenue Contract Waterfalls</relationshipLabel>
    <relationshipName>Revenue_Contract_Waterfalls</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Revenue_Contract_Waterfall__c/fields/Revenue_Contract_Line__c.field-meta.xml
<CustomField>
    <fullName>Revenue_Contract_Line__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Revenue Contract Line</label>
    <referenceTo>Revenue_Contract_Line__c</referenceTo>
    <relationshipLabel>Revenue Contract Waterfalls</relationshipLabel>
    <relationshipName>Revenue_Contract_Waterfalls</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/TestDataFactory.cls
@IsTest
public class TestDataFactory {
    //Method to create Revenue Contract
    public static List<Revenue_Contract__c> createRevenueContract(Integer numOfRecords) {
        List<Revenue_Contract__c> lstRecords = new list<Revenue_Contract__c>();
        for (Integer i = 0; i < numOfRecords; i++) {
            lstRecords.add(new Revenue_Contract__c(
                Name = 'TestRevenueContract' + i, 
                Revenue_Contract_GUID__c = '123', 
                Bg_Run_ID__c = 'Test'
            ));
        }
        return lstRecords;
    }

    /*Method to create Test Revenue Contract Line Data*/
    public static List<Revenue_Contract_Line__c> createRevenueContractLine(integer numOfRecords) {
        List<Revenue_Contract_Line__c> lstRecords = new List<Revenue_Contract_Line__c>();
        for (integer i = 0; i < numOfRecords; i++) {
            lstRecords.add(new Revenue_Contract_Line__c(
                Line_Term__c = 3, 
                Terms__c = 12, 
                Bg_Run_ID__c = 'Test'
            ));// Name is not writeable
        }
        return lstRecords;
    }

    //method to create Revenue Contract Waterfall records
    public static List<Revenue_Contract_Waterfall__c> createRevenueContractWaterfall(Integer numOfRecords) {
        List<Revenue_Contract_Waterfall__c> lstRecords = new List<Revenue_Contract_Waterfall__c>();
        for (Integer i = 0; i < numOfRecords; i++) {
            lstRecords.add(new Revenue_Contract_Waterfall__c(
                Bg_Run_ID__c = 'Test'
            ));
        }
        return lstRecords;
    }

    //method to create Revenue Summary records
    public static List<Rev_Summary__c> createRevenueSummary(Integer numOfRecords) {
        List<Rev_Summary__c> lstRecords = new List<Rev_Summary__c>();
        for (Integer i = 0; i < numOfRecords; i++) {
            lstRecords.add(new Rev_Summary__c(
                Bg_Run_ID__c = 'Test'
            ));
        }
        return lstRecords;
    }

    //method to create Line Metric Dimension records
    public static List<Line_Met_Dimension__c> createLineMetricDimension(Integer numOfRecords) {
        List<Line_Met_Dimension__c> lstRecords = new List<Line_Met_Dimension__c>();
        for (Integer i = 0; i < numOfRecords; i++) {
            lstRecords.add(new Line_Met_Dimension__c(
                Bg_Run_ID__c = 'Test'
            ));
        }
        return lstRecords;
    }

}