force-app/main/default/objects/Line_Met_Dimension__c/Line_Met_Dimension__c.object-meta.xml
<CustomObject>
    <label>Line Metric Dimension</label>
    <nameField>
        <displayFormat>LMD-{0000}</displayFormat>
        <label>Line Metric Dimension Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Line Metric Dimensions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Line_Met_Dimension__c/fields/Revenue_Contract_Line__c.field-meta.xml
<CustomField>
    <fullName>Revenue_Contract_Line__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Revenue Contract Line</label>
    <referenceTo>Revenue_Contract_Line__c</referenceTo>
    <relationshipLabel>Line Metric Dimensions</relationshipLabel>
    <relationshipName>Line_Met_Dimensions</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Rev_Summary__c/Rev_Summary__c.object-meta.xml
<CustomObject>
    <label>Revenue Summary</label>
    <nameField>
        <displayFormat>RS-{00000}</displayFormat>
        <label>Revenue Summary Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Revenue Summary</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Revenue_Contract__c/Revenue_Contract__c.object-meta.xml
<CustomObject>
    <label>Revenue Contract</label>
    <nameField>
        <label>Revenue Contract Id</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Revenue Contracts</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Revenue_Contract_Line__c/Revenue_Contract_Line__c.object-meta.xml
<CustomObject>
    <label>Revenue Contract Line</label>
    <nameField>
        <displayFormat>RCL-{00000}</displayFormat>
        <label>RC Line ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Revenue Contract Lines</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Revenue_Contract_Waterfall__c/Revenue_Contract_Waterfall__c.object-meta.xml
<CustomObject>
    <label>Revenue Contract Waterfall</label>
    <nameField>
        <displayFormat>WF-{000}</displayFormat>
        <label>Revenue Waterfall Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Revenue Contract Waterfalls</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Revenue_Contract_Waterfall__c/fields/Revenue_Contract_Line__c.field-meta.xml
<CustomField>
    <fullName>Revenue_Contract_Line__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Revenue Contract Line</label>
    <referenceTo>Revenue_Contract_Line__c</referenceTo>
    <relationshipLabel>Revenue Contract Waterfalls</relationshipLabel>
    <relationshipName>Revenue_Contract_Waterfalls</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/RCJsonInbound.cls
@RestResource(urlMapping = '/RCJson/*')
global with sharing class RCJsonInbound {
    @HttpDelete
    global static void doDelete() {
        RestRequest req = RestContext.request;
        RestResponse res = RestContext.response;
        Map<String, String> mapResult = new Map<String, String>();
        try {
            String strRunId = req.requestURI.substring(req.requestURI.lastIndexOf('/') + 1);
            List<Id> lstJobIds = new List<Id>();
            Map<String, Object> mapResponse = (Map<String, Object>)JSON.deserializeUntyped(req.requestBody.toString());
            List<Object> lstRCs = (List<Object>)mapResponse.get('revenue_contract_id');
            List<String> lstRCNumbers = new List<String>();
            for (Object rcNumber : lstRCs) {
                lstRCNumbers.add((String) rcNumber);
            }
            lstJobIds.add(initiateDeleteBatch(lstRCNumbers, strRunId, 'Revenue_Contract__c'));
            lstJobIds.add(initiateDeleteBatch(lstRCNumbers, strRunId, 'Revenue_Contract_Waterfall__c'));
            lstJobIds.add(initiateDeleteBatch(lstRCNumbers, strRunId, 'Rev_Summary__c'));
            lstJobIds.add(initiateDeleteBatch(lstRCNumbers, strRunId, 'Line_Met_Dimension__c'));
            lstJobIds.add(initiateDeleteBatch(lstRCNumbers, strRunId, 'Revenue_Contract_Line__c'));
            mapResult.put('Status', 'OPERATION ENQUEUED');
            mapResult.put('JobIds', JSON.serialize(lstJobIds));
            res.statusCode = 200;
        } catch (Exception ex) {
            res.statusCode = 400;
            mapResult.put('Status', 'FAILED');
            mapResult.put('Details', ex.getMessage() + '' + ex.getStackTraceString());
        }
        res.responseBody = Blob.valueOf(JSON.serialize(mapResult));
    }

    private static Id initiateDeleteBatch(List<String> lstRCNumbers, String strRunId, String strObjName) {
        return RCJsonDeleteBatch.executeBatch(lstRCNumbers, strRunId, strObjName);
    }

}